services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:16-3.4
    container_name: gis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gis_carbon
      POSTGRES_USER: gis_user
      POSTGRES_PASSWORD: gis_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - gis_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gis_user -d gis_carbon"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: gis_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gis_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gis_django
    restart: unless-stopped
    environment:
      - DEBUG=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_DATABASE=gis_carbon
      - DB_USER=gis_user
      - DB_PASSWORD=gis_password
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - django_static:/usr/src/static
      - django_media:/usr/src/media
      - ./backend/user_id.json:/usr/src/app/user_id.json
      - ./GEE_notebook_Forestry:/usr/src/app/gee_lib
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gis_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI for GEE Tile Service
  fastapi:
    build:
      context: ./fastapi-gee-service
      dockerfile: Dockerfile
    container_name: gis_fastapi
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/1
      - POSTGRES_URL=postgresql://gis_user:gis_password@postgres:5432/gis_carbon_data
      - GEE_SERVICE_ACCOUNT=iqbalpythonapi@bukit30project.iam.gserviceaccount.com
    volumes:
      - ./backend/user_id.json:/app/user_id.json
      - gee_tiles_cache:/app/cache
      - /Users/miqbalf/gis-carbon-ai/GEE_notebook_Forestry:/app/gee_lib:ro
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gis_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GeoServer
  geoserver:
    image: kartoza/geoserver:2.24.0
    container_name: gis_geoserver
    restart: unless-stopped
    environment:
      - GEOSERVER_ADMIN_PASSWORD=admin
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_LOG_LEVEL=INFO
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_OPTS=-Xms512m -Xmx2048m
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./geoserver/config:/opt/geoserver/data_dir
    ports:
      - "8080:8080"
    networks:
      - gis_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MapStore (Latest Official Docker Image with PostgreSQL)
  mapstore:
    image: geosolutionsit/mapstore2:v2025.01.02-stable
    container_name: gis_mapstore
    restart: unless-stopped
    environment:
      - CATALINA_OPTS=-Xms512m -Xmx2048m -Dgeostore-ovr=file:///usr/local/tomcat/conf/geostore-datasource-ovr.properties
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
    volumes:
      - ./mapstore/geostore-datasource-ovr-postgres.properties:/usr/local/tomcat/conf/geostore-datasource-ovr.properties
    ports:
      - "8082:8080"
    networks:
      - gis_network
    depends_on:
      - postgres
      - geoserver

  # Jupyter Lab for testing and development
  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: gis_jupyter
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app:/app/gee_lib:/app/ex_ante
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      - JUPYTER_ALLOW_ROOT=1
    volumes:
      - ./jupyter/notebooks:/app/notebooks
      - ./jupyter/data:/app/data
      - ./jupyter/shared:/app/shared
      - ./backend/user_id.json:/app/user_id.json
      - /Users/miqbalf/gis-carbon-ai/GEE_notebook_Forestry:/app/gee_lib:ro
      - /Users/miqbalf/gis-carbon-ai/ex_ante:/app/ex_ante:ro
    ports:
      - "8888:8888"
    networks:
      - gis_network
    depends_on:
      - postgres
      - redis
      - geoserver

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: gis_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - django_static:/var/www/static
      - django_media:/var/www/media
    depends_on:
      - django
      - fastapi
      - geoserver
      - mapstore
    networks:
      - gis_network

volumes:
  postgres_data:
  redis_data:
  django_static:
  django_media:
  geoserver_data:
  gee_tiles_cache:

networks:
  gis_network:
    driver: bridge
